-- AlterEnum
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'NEEDS_INFO' AFTER 'INTERVIEW';

-- AlterTable
ALTER TABLE "MembershipApplication"
ADD COLUMN "reviewNote" TEXT,
ADD COLUMN "reviewedAt" TIMESTAMP(3),
ADD COLUMN "canReapply" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "decidedAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
